# Generated by Django 6.0 on 2025-12-17 03:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('experiences', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Inquiry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=120)),
                ('email', models.EmailField(max_length=254)),
                ('company', models.CharField(blank=True, max_length=160)),
                ('timeline', models.CharField(blank=True, max_length=120)),
                ('message', models.TextField()),
                ('referrer', models.CharField(blank=True, max_length=160)),
                ('processed', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='StudioSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('studio_name', models.CharField(default='Giftorium', max_length=120)),
                ('eyebrow', models.CharField(default='Portfolio First', max_length=120)),
                ('tagline', models.CharField(default='Immersive environments for bold cultural moments', max_length=200)),
                ('intro', models.TextField(default='Giftorium collaborates with museums, brands, and cultural leaders to craft sensorial experiences that guests remember well after the lights dim.')),
                ('hero_note', models.CharField(blank=True, default='Each commission is built as a cinematic atmosphere. Scroll to explore.', max_length=200)),
                ('cta_label', models.CharField(default='Start a collaboration', max_length=80)),
                ('logo', models.ImageField(blank=True, upload_to='brand/')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Studio settings',
                'verbose_name_plural': 'Studio settings',
            },
        ),
        migrations.CreateModel(
            name='TeamMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=120)),
                ('role', models.CharField(max_length=160)),
                ('bio', models.TextField()),
                ('headshot', models.ImageField(blank=True, upload_to='team/')),
                ('order', models.PositiveIntegerField(default=0)),
                ('social_link', models.URLField(blank=True)),
            ],
            options={
                'ordering': ['order', 'name'],
            },
        ),
    ]
