# Generated by Django 6.0 on 2025-12-17 03:49

from django.db import migrations


def seed_team_members(apps, schema_editor):
    TeamMember = apps.get_model('experiences', 'TeamMember')
    members = [
        {
            "name": "Milad Ameri",
            "role": "Creative Director",
            "bio": "Leads narrative development and experiential direction across hospitality, culture, and technology partners.",
            "order": 1,
        },
        {
            "name": "Amir Parsa",
            "role": "Executive Producer",
            "bio": "Oversees production, technical partnerships, and on-site execution for large-scale build-outs.",
            "order": 2,
        },
    ]
    for payload in members:
        TeamMember.objects.get_or_create(name=payload["name"], defaults=payload)


def remove_team_members(apps, schema_editor):
    TeamMember = apps.get_model('experiences', 'TeamMember')
    TeamMember.objects.filter(name__in=["Milad Ameri", "Amir Parsa"]).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('experiences', '0002_inquiry_studiosettings_teammember'),
    ]

    operations = [
        migrations.RunPython(seed_team_members, remove_team_members),
    ]
