# Generated by Django 6.0 on 2025-12-17 03:56

from django.db import migrations


def update_team_roles(apps, schema_editor):
    TeamMember = apps.get_model('experiences', 'TeamMember')
    updates = {
        "Milad Ameri": {
            "role": "Technology & Strategy Lead",
            "bio": (
                "Architects the technical stack, innovation roadmap, and partner strategy "
                "for every Giftorium build."
            ),
        },
        "Amir Parsa": {
            "role": "Creative Director",
            "bio": (
                "Sets the creative vision and guides spatial storytelling, scenography, and "
                "sensory direction."
            ),
        },
    }
    for name, payload in updates.items():
        TeamMember.objects.filter(name=name).update(**payload)


def revert_team_roles(apps, schema_editor):
    TeamMember = apps.get_model('experiences', 'TeamMember')
    previous = {
        "Milad Ameri": {
            "role": "Creative Director",
            "bio": (
                "Leads narrative development and experiential direction across hospitality, "
                "culture, and technology partners."
            ),
        },
        "Amir Parsa": {
            "role": "Executive Producer",
            "bio": (
                "Oversees production, technical partnerships, and on-site execution for "
                "large-scale build-outs."
            ),
        },
    }
    for name, payload in previous.items():
        TeamMember.objects.filter(name=name).update(**payload)


class Migration(migrations.Migration):

    dependencies = [
        ('experiences', '0003_seed_team_members'),
    ]

    operations = [
        migrations.RunPython(update_team_roles, revert_team_roles),
    ]
