# Generated by GitHub Copilot (GPT-5.1-Codex) on 2025-12-18

from django.db import migrations


SLUG = "yalda-hafez-faal-capsule"


def seed_portfolio_item(apps, schema_editor):
    PortfolioItem = apps.get_model('experiences', 'PortfolioItem')
    PortfolioImage = apps.get_model('experiences', 'PortfolioImage')

    item, _ = PortfolioItem.objects.get_or_create(
        slug=SLUG,
        defaults={
            "title": "Yalda Hafez Faal Keepsake Capsule",
            "medium": "Scented merch + printed keepsakes",
            "description": (
                "A limited merch drop created for the CBC Yalda celebration. "
                "We translated the ritual of pulling a Hafez verse into a tactile retail "
                "moment, layering foil, night/day palettes, and keepsake packaging so "
                "guests leave with an artifact of the gathering."
            ),
            "location": "Toronto, ON",
            "year": "2024",
            "hero_image": "portfolio/hero/Tote Bag Model.jpg",
            "outcome": (
                "Sold out the full capsule in under two hours and extended the event "
                "storytelling through take-home pieces guests continue to photograph and share."
            ),
            "featured": True,
        },
    )

    gallery_assets = [
        ("image_2025-12-17_11-44-23.png", "Foiled night-and-day key art explorations"),
        ("image_2025-12-17_11-44-39.png", "Graphic system sketching the pull-tab ritual"),
        ("image_2025-12-17_11-44-48.png", "Palette refinements for the keepsake objects"),
        ("Sticker Bar 1.png", "Sticker bar concept pairing Persian typography with constellations"),
        ("Sticker Bar 2.png", "Secondary sticker bar focusing on poem fragments"),
        ("Magnet - Sticker 1 (Night).jpg", "Night edition magnet featuring eclipse gradient"),
        ("Magnet - Sticker 1 (SHAB).jpg", "Shab edition magnet pairing calligraphy with copper edges"),
        ("Magnet - Sticker 2 (NIGHT).jpg", "Night edition magnet highlighting the poem reveal"),
        ("Magnet - Sticker 2 (SHAB).jpg", "Shab edition magnet with neon typographic lockup"),
        ("Magnet - Sticker 3 (NIGHT).jpg", "Night edition magnet showing constellations over velvet"),
        ("Magnet - Sticker 3 (SHAB).jpg", "Shab edition magnet showing ivory foiling"),
        ("Magnet - Sticker 4.jpg", "Modular magnet referencing the Hafez poem cards"),
        ("Magnet - Sticker 5 (NIGHT).jpg", "Night edition magnet with metallic ink flood"),
        ("Magnet - Sticker 5 (SHAB).jpg", "Shab edition magnet with sunlit palette"),
        ("Totebag (NIGHT).jpg", "Night version tote with oversized poetry pull"),
        ("Totebag (SHAB).jpg", "Day version tote with copper embroidery"),
        ("Tote Bag Model 2.jpg", "Hero tote styling with wardrobe coordination"),
        ("Tote Bag Model 3.jpg", "Alternate tote styling highlighting straps"),
    ]

    for order, (filename, alt_text) in enumerate(gallery_assets, start=1):
        image_path = f"portfolio/gallery/{filename}"
        photo, created = PortfolioImage.objects.get_or_create(
            item=item,
            image=image_path,
            defaults={
                "alt_text": alt_text,
                "order": order,
            },
        )
        if not created:
            photo.alt_text = alt_text
            photo.order = order
            photo.save(update_fields=["alt_text", "order"])


def remove_portfolio_item(apps, schema_editor):
    PortfolioItem = apps.get_model('experiences', 'PortfolioItem')
    PortfolioItem.objects.filter(slug=SLUG).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('experiences', '0004_update_team_roles'),
    ]

    operations = [
        migrations.RunPython(seed_portfolio_item, remove_portfolio_item),
    ]
