# Generated by GitHub Copilot (GPT-5.1-Codex) on 2025-12-18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('experiences', '0005_seed_portfolio_item'),
    ]

    operations = [
        migrations.AddField(
            model_name='portfolioitem',
            name='grid_image',
            field=models.ImageField(blank=True, upload_to='portfolio/grid/'),
        ),
    ]
