# Generated by GitHub Copilot (GPT-5.1-Codex) on 2025-12-18

from django.db import migrations


def set_grid_assets(apps, schema_editor):
    PortfolioItem = apps.get_model('experiences', 'PortfolioItem')
    PortfolioItem.objects.filter(slug='yalda-hafez-faal-capsule').update(
        grid_image='portfolio/grid/yalda-card.jpg'
    )


def unset_grid_assets(apps, schema_editor):
    PortfolioItem = apps.get_model('experiences', 'PortfolioItem')
    PortfolioItem.objects.filter(slug='yalda-hafez-faal-capsule').update(grid_image='')


class Migration(migrations.Migration):

    dependencies = [
        ('experiences', '0006_portfolioitem_grid_image'),
    ]

    operations = [
        migrations.RunPython(set_grid_assets, unset_grid_assets),
    ]
