# Generated by GitHub Copilot (GPT-5.1-Codex) on 2025-12-18

from django.db import migrations


SLUG = 'yalda-hafez-faal-capsule'
GALLERY_PAYLOAD = [
    ('portfolio/gallery/yalda-artwork-01.png', 'Primary lockup illustration exploring light bleed'),
    ('portfolio/gallery/yalda-artwork-02.png', 'Secondary artwork study layering constellations'),
    ('portfolio/gallery/yalda-artwork-03.png', 'Color refinement boards for the capsule packaging'),
    ('portfolio/gallery/yalda-magnet-01.jpg', 'Night edition magnet with eclipse gradient'),
    ('portfolio/gallery/yalda-magnet-02.jpg', 'Silver-foil magnet highlighting poem pull cards'),
    ('portfolio/gallery/yalda-magnet-05.jpg', 'Copper foil magnet from the nocturnal palette'),
    ('portfolio/gallery/yalda-stickerbar-01.png', 'Sticker bar system mixing typography + astral cues'),
    ('portfolio/gallery/yalda-stickerbar-02.png', 'Alternate sticker bar emphasizing Hafez verses'),
    ('portfolio/gallery/yalda-tote-angled.jpg', 'Tote styled at angle showing oversized print'),
    ('portfolio/gallery/yalda-tote-detail.jpg', 'Detail crop focusing on embroidery and straps'),
    ('portfolio/gallery/yalda-tote-night.jpg', 'Night-lit tote version shot on deep backdrop'),
]


def refresh_portfolio_assets(apps, schema_editor):
    PortfolioItem = apps.get_model('experiences', 'PortfolioItem')
    PortfolioImage = apps.get_model('experiences', 'PortfolioImage')

    try:
        item = PortfolioItem.objects.get(slug=SLUG)
    except PortfolioItem.DoesNotExist:
        return

    item.hero_image.name = 'portfolio/hero/yalda-hero.jpg'
    item.grid_image = 'portfolio/grid/yalda-grid.jpg'
    item.save(update_fields=['hero_image', 'grid_image'])

    PortfolioImage.objects.filter(item=item).delete()
    frames = [
        PortfolioImage(
            item=item,
            image=path,
            alt_text=alt,
            order=index,
        )
        for index, (path, alt) in enumerate(GALLERY_PAYLOAD, start=1)
    ]
    PortfolioImage.objects.bulk_create(frames)


def revert_portfolio_assets(apps, schema_editor):
    PortfolioItem = apps.get_model('experiences', 'PortfolioItem')
    PortfolioImage = apps.get_model('experiences', 'PortfolioImage')

    try:
        item = PortfolioItem.objects.get(slug=SLUG)
    except PortfolioItem.DoesNotExist:
        return

    PortfolioImage.objects.filter(item=item).delete()
    item.grid_image = ''
    item.save(update_fields=['grid_image'])


class Migration(migrations.Migration):

    dependencies = [
        ('experiences', '0007_set_portfolio_grid_images'),
    ]

    operations = [
        migrations.RunPython(refresh_portfolio_assets, revert_portfolio_assets),
    ]
