# Generated by Django 6.0 on 2025-12-18 07:56

from django.db import migrations, models


OLD_TAGLINE = "Immersive environments for bold cultural moments"
NEW_TAGLINE = "Immersive environments for ambitious event launches"
OLD_INTRO = "Giftorium collaborates with museums, brands, and cultural leaders to craft sensorial experiences that guests remember well after the lights dim."
NEW_INTRO = (
    "Giftorium partners with event, brand, and creative teams to build sensorial experiences "
    "that guests remember long after strike."
)


def update_studio_copy(apps, schema_editor):
    StudioSettings = apps.get_model('experiences', 'StudioSettings')
    StudioSettings.objects.filter(tagline=OLD_TAGLINE).update(tagline=NEW_TAGLINE)
    StudioSettings.objects.filter(intro=OLD_INTRO).update(intro=NEW_INTRO)


def revert_studio_copy(apps, schema_editor):
    StudioSettings = apps.get_model('experiences', 'StudioSettings')
    StudioSettings.objects.filter(tagline=NEW_TAGLINE).update(tagline=OLD_TAGLINE)
    StudioSettings.objects.filter(intro=NEW_INTRO).update(intro=OLD_INTRO)


class Migration(migrations.Migration):

    dependencies = [
        ('experiences', '0008_refresh_yalda_assets'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studiosettings',
            name='intro',
            field=models.TextField(default='Giftorium partners with event, brand, and creative teams to build sensorial experiences that guests remember long after strike.'),
        ),
        migrations.AlterField(
            model_name='studiosettings',
            name='tagline',
            field=models.CharField(default='Immersive environments for ambitious event launches', max_length=200),
        ),
        migrations.RunPython(update_studio_copy, revert_studio_copy),
    ]
